SceauBundle\Entity\Actualite:
    type: entity
    table: Actualite
    repositoryClass: SceauBundle\Entity\Repository\ActualiteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        introduction:
            type: string
            length: 255
        content:
            type: text
        date:
            type: datetimetz
        active:
            type: boolean
    lifecycleCallbacks: {  }
