<?php

namespace SceauBundle\Entity\Repository;

/**
 * ActiviteProfessionnelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteProfessionnelleRepository extends \Doctrine\ORM\EntityRepository
{
}
