<?php

namespace SceauBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ArticlePresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlePresseRepository extends EntityRepository
{
    public function getAllArticlePresse()
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder->where('a.published = true')
                     ->orderBy('a.date', 'DESC')
        ;

        return $queryBuilder->getQuery()->getResult();
    }




}
