<?php

namespace SceauBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeParametrageCSVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeCSVParametrageRepository extends EntityRepository
{
}
