<?php

namespace SceauBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
    public function getDateConfirmation($poEmail)
    {
        $loQuery = $this->createQueryBuilder('e')
            ->select('e')
            ->where('e.email = :email')
            ->setParameter('email', $poEmail);
        return $loQuery->getQuery()->getOneOrNullResult();
    }
}
