<?php

namespace SceauBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends EntityRepository
{
    /**
     * Function pour retourner l'utilisateur par rapport a son pseudo
     * @param type $poEmail
     * @return type
     */
    public function getByMail($poEmail) {
        $loQuery = $this->createQueryBuilder('m')
                        ->select('m')
                        ->Join('m.emails', 'e')
                        ->Where('e.email = :email')
                        ->andWhere('e.principal = true')
                        ->setParameter('email', $poEmail);
        return $loQuery->getQuery()->getOneOrNullResult();
    }
    
    /**
     * Function pour retourner l'utilisateur par rapport a son pseudo
     * @param type $poPseudo
     * @return type
     */
    public function getByPseudo($poPseudo) {
        $loQuery = $this->createQueryBuilder('m')
                        ->select('m')
                        ->Where('m.pseudo = :pseudo')
                        ->setParameter('pseudo', $poPseudo)
                        ->setMaxResults(1);
        return $loQuery->getQuery()->getOneOrNullResult();
        
    }
}
