<?php

namespace SceauBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends EntityRepository
{
    public function getByMail($poEmail) {
        $loQuery = $this->createQueryBuilder('m')
                        ->select('m')
                        ->Join('m.emails', 'e')
                        ->Where('e.email = :email')
                        ->andWhere('e.principal = true')
                        ->setParameter('email', $poEmail);
        return $loQuery->getQuery()->getOneOrNullResult();
    }
}
