<?php

namespace SceauBundle\Entity\Repository;

/**
 * NewslettersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewslettersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastNewsLetters() {
        $loQuery = $this->createQueryBuilder('nl')
                        ->select('nl')
                        ->orderBy('nl.id', 'DESC')
                        ->setMaxResults(3);
        return $loQuery->getQuery()->getResult();
    }
}
