<?php

namespace SceauBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewslettersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewslettersRepository extends EntityRepository
{
    public function getLastNewsLetters($loLimte)
    {
        $loQuery = $this->createQueryBuilder('nl')
                        ->select('nl')
                        ->orderBy('nl.id', 'DESC')
                        ->setMaxResults($loLimte);

        return $loQuery->getQuery()->getResult();
    }
}
