<?php

namespace SceauBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceClientelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceClientelRepository extends EntityRepository
{
}
