<?php

namespace SceauBundle\Entity\Repository;

/**
 * SituationFamilialeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituationFamilialeRepository extends \Doctrine\ORM\EntityRepository
{
}
