<?php

namespace SceauBundle\Entity\Repository;

/**
 * TicketHistoriqueEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketHistoriqueEmailRepository extends \Doctrine\ORM\EntityRepository
{
}
