<?php

namespace SceauBundle\Entity\Repository;

/**
 * TombolaTirageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TombolaTirageRepository extends \Doctrine\ORM\EntityRepository
{
}
