<?php

namespace SceauBundle\Entity\Repository;

/**
 * TombolaGainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TombolaGainRepository extends \Doctrine\ORM\EntityRepository
{
}
