<?php

namespace SceauBundle\Entity\Repository;

/**
 * TombolaTirageStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TombolaTirageStateRepository extends \Doctrine\ORM\EntityRepository
{
}
