<?php

namespace SceauBundle\Entity\Repository;

/**
 * TombolaSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TombolaSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
