<?php

namespace SceauBundle\Entity\Repository;

/**
 * TombolaTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TombolaTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
