<?php

namespace SceauBundle\Entity\Repository;

/**
 * TombolaTirageGagnantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TombolaTirageGagnantRepository extends \Doctrine\ORM\EntityRepository
{
}
