imports:
    - { resource: config_dev.yml }

framework:
    validation:
        cache: apc

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc
    dbal:
        host: loki
        port: 5439
        dbname: sceau
        user: sceau_user
        password: hello

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

# Surcharge des paramètres
parameters:
    extranet_protocole: http