imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

doctrine:
    dbal:
        host:  127.0.0.1
        port: 5432
        dbname: sceau
        user: sceau
        password: sceau

bazinga_faker:
    orm: doctrine
    locale: fr_FR
    entities:
        FIANET\SceauBundle\Entity\Package:
            number: 5
            custom_formatters:
                libelle: {method: sentence, parameters: [2]}
                actif: {method: boolean, parameters: [100]}
        FIANET\SceauBundle\Entity\OptionType:
            number: 5
        FIANET\SceauBundle\Entity\Option:
            number: 5
            custom_formatters:
                libelle: {method: sentence, parameters: [2] }
                actif: {method: boolean, parameters: [100]}
        FIANET\SceauBundle\Entity\PackageOption:
            number: 5
        FIANET\SceauBundle\Entity\Societe:
            number: 1000
            custom_formatters:
                libelle: {method: word }
        FIANET\SceauBundle\Entity\SiteType:
            number: 5
            custom_formatters:
                libelle: {method: word }
        FIANET\SceauBundle\Entity\AdministrationType:
            number: 5
            custom_formatters:
                libelle: {method: word }
        FIANET\SceauBundle\Entity\Site:
            number: 1000
            custom_formatters:
                nom: {method: word }
                url: {method: url }
                slug: {method: slug }
                clePrivee: {method: numerify, parameters: ['##############'] }
                sitePrincipal: {method: null}
        FIANET\SceauBundle\Entity\FluxStatut:
            number: 4
            custom_formatters:
                libelle: {method: randomElement, parameters: [ [ 'A traiter', 'En cours de traitement', 'Traité et valide', 'Traité et invalide' ] ], unique: true}
        FIANET\SceauBundle\Entity\Flux:
            number: 2000
            custom_formatters:
                checksum: {method: md5, unique: true}
                ip:  {method: ipv4}
                dateInsertion: {method: dateTimeThisYear}
                libelleErreur:  {method: null}
        FIANET\SceauBundle\Entity\DelaiEnvoi:
            number: 10
            custom_formatters:
                nbJours: {method: numberBetween, parameters: [1,45] }
        FIANET\SceauBundle\Entity\DelaiReception:
            number: 10
            custom_formatters:
                nbJours: {method: numberBetween, parameters: [1,45] }
        FIANET\SceauBundle\Entity\QuestionnaireType:
            number: 10
            custom_formatters:
                libelle: {method: word}
                questionnaireType: {method: null}
                parametrage: {method: lexify, parameters: ['{???}'] }
                nbJoursPourRepondre: {method: numberBetween, parameters: [30,90] }
        FIANET\SceauBundle\Entity\QuestionnairePersonnalisation:
            number: 1000
            custom_formatters:
                dateDebut: {method: dateTimeThisYear}
                dateFin:  {method: null}
        FIANET\SceauBundle\Entity\Langue:
            number: 4
            custom_formatters:
                code: {method: lexify, parameters: ['???'] }
                libelle: {method: word}
        FIANET\SceauBundle\Entity\QuestionType:
            number: 5
            custom_formatters:
                libelle: {method: sentence, parameters: [2] }
        FIANET\SceauBundle\Entity\Question:
            number: 200
            custom_formatters:
                libelle: {method: sentence, parameters: [2]}
                libelleCourt: {method: sentence, parameters: [1]}
                texteSupp: {method: null}
                ordre: {method: numberBetween, parameters: [0,200]}
                dateDebut: {method: null}
                dateFin: {method: null}
                page: {method: numberBetween, parameters: [1,10]}
                actif: {method: boolean, parameters: [100]}
                cache: {method: boolean, parameters: [0]}
                visible: {method: null}
                obligatoire: {method: boolean, parameters: [0]}
        FIANET\SceauBundle\Entity\Reponse:
            number: 500
            custom_formatters:
                libelle: {method: sentence, parameters: [2]}
                libelleCourt: {method: sentence, parameters: [1]}
                ordre: {method: numberBetween, parameters: [0,200]}
                precision: {method: boolean, parameters: [0]}
                actif: {method: boolean, parameters: [100]}
        FIANET\SceauBundle\Entity\Commande:
            number: 2000
            custom_formatters:
                email: {method: email }
                prenom: {method: firstName }
                nom: {method: lastName }
                date: {method: dateTimeThisYear }
                reference: {method: numerify, parameters: ['##########'] }
                montant: {method: randomFloat, parameters: [2] }
                dateutilisation : {method: null }
                donnees : {method: null }
        FIANET\SceauBundle\Entity\Questionnaire:
            number: 2000
            custom_formatters:
                membre: {method: null }
                email: {method: email }
                dateInsertion: {method: dateTimeThisYear }
                datePrevEnvoi: {method: dateTimeThisYear }
                dateEnvoi: {method: dateTimeThisYear }
                dateOuverture: {method: dateTimeThisYear }
                dateReponse: {method: dateTimeThisYear }
                datePrevRelance: {method: null }
                dateRelance: {method: null }
                actif: {method: boolean, parameters: [100]}
                sousSite: {method: null }
        FIANET\SceauBundle\Entity\QuestionnaireReponse:
            number: 5000
            custom_formatters:
                commentaire: {method: text, parameters: [500]}
                note: {method: numberBetween, parameters: [1,10]}

# Surcharge des paramètres
parameters:
    extranet_protocole: http

    # Pour les lignes de commandes
    router.request_context.host: localhost
    router.request_context.scheme: http
    router.request_context.base_url: /Sceau/app_dev.php