imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: extranet.yml }
    - { resource: moteur.yml }
    - { resource: emails.yml }
    - { resource: doctrine_extensions.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 1
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ['SceauBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        types:
            jsonb_array: SceauBundle\Doctrine\DBAL\Types\JsonbArrayType

        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                mapping_types:
                    jsonb: jsonb_array

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            # Doctrine extensions
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity/MappedSuperclass"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

# Monolog Configuration
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            channels: [!import_csv]
        nested:
            type: rotating_file
            max_files: 30
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        import_csv:
            type: fingers_crossed
            action_level: info
            handler: import_csv_handler
            channels: [import_csv]
        import_csv_handler:
            type: rotating_file
            max_files: 30
            path: "%kernel.logs_dir%/import_csv.%kernel.environment%.log"
            level: debug

# Memcached Configuration
lsw_memcache:
    session:
        pool: default
    pools:
        default:
            servers:
              - { host: 10.199.54.106, tcp_port: 11211 }
    doctrine:
        metadata_cache:
            pool: default
            entity_manager: default
        result_cache:
            pool: default
            entity_manager: default
        query_cache:
            pool: default
            entity_manager: default