imports:
    - { resource: config.yml }

framework:
    validation:
        cache: apc

doctrine:
    dbal:
        host: loki
        port: 5439
        dbname: sceau
        user: sceau_user
        password: hello