imports:
    - { resource: config.yml }

framework:
    validation:
        cache: apc

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc
    dbal:
        host: loki
        port: 5439
        dbname: sceau
        user: sceau_user
        password: hello