imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

# Monolog Configuration
monolog:
    handlers:
        main:
            type: rotating_file
            max_files: %logger_nb_max_fichier%
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        import_csv:
            type: fingers_crossed
            action_level: debug
            handler: import_csv_handler
            channels: [import_csv]
        import_csv_handler:
            type: rotating_file
            max_files: %logger_nb_max_fichier%
            path: "%kernel.logs_dir%/import_csv.%kernel.environment%.log"
            level: debug
        validation_flux:
            type: fingers_crossed
            action_level: debug
            handler: validation_flux_handler
            channels: [validation_flux]
        validation_flux_handler:
            type: rotating_file
            max_files: %logger_nb_max_fichier%
            path: "%kernel.logs_dir%/flux.%kernel.environment%.log"
            level: debug
assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

doctrine:
    dbal:
        host:  loki
        port: 5439
        dbname: sceau
        user: sceau_user
        password: hello

bazinga_faker:
    orm: doctrine
    locale: fr_FR
    entities:
        SceauBundle\Entity\Package:
            number: 5
            custom_formatters:
                libelle: {method: sentence, parameters: [2]}
                actif: {method: boolean, parameters: [100]}
        SceauBundle\Entity\OptionType:
            number: 5
        SceauBundle\Entity\Option:
            number: 5
            custom_formatters:
                libelle: {method: sentence, parameters: [2] }
                actif: {method: boolean, parameters: [100]}
        SceauBundle\Entity\PackageOption:
            number: 5
        SceauBundle\Entity\Societe:
            number: 500
            custom_formatters:
                libelle: {method: word }
        SceauBundle\Entity\SiteType:
            number: 5
            custom_formatters:
                libelle: {method: word }
        SceauBundle\Entity\AdministrationType:
            number: 5
            custom_formatters:
                libelle: {method: word }
        SceauBundle\Entity\Site:
            number: 500
            custom_formatters:
                nom: {method: word }
                url: {method: url }
                slug: {method: slug }
                clePrivee: {method: numerify, parameters: ['##############'] }
                sitePrincipal: {method: null}
        SceauBundle\Entity\FluxStatut:
            number: 4
            custom_formatters:
                libelle: {method: randomElement, parameters: [ [ 'A traiter', 'En cours de traitement', 'Traité et valide', 'Traité et invalide' ] ], unique: true}
        SceauBundle\Entity\Flux:
            number: 1000
            custom_formatters:
                checksum: {method: md5, unique: true}
                ip:  {method: ipv4}
                dateInsertion: {method: dateTimeThisYear}
                libelleErreur:  {method: null}
        SceauBundle\Entity\DelaiEnvoi:
            number: 10
            custom_formatters:
                nbJours: {method: numberBetween, parameters: [1,45] }
        SceauBundle\Entity\DelaiReception:
            number: 10
            custom_formatters:
                nbJours: {method: numberBetween, parameters: [1,45] }
        SceauBundle\Entity\QuestionnaireType:
            number: 10
            custom_formatters:
                libelle: {method: word}
                questionnaireType: {method: null}
                parametrage: {method: lexify, parameters: ['{???}'] }
                nbJoursPourRepondre: {method: numberBetween, parameters: [30,90] }
        SceauBundle\Entity\QuestionnairePersonnalisation:
            number: 500
            custom_formatters:
                dateDebut: {method: dateTimeThisYear}
                dateFin:  {method: null}
        SceauBundle\Entity\Langue:
            number: 4
            custom_formatters:
                code: {method: lexify, parameters: ['???'] }
                libelle: {method: word}
        SceauBundle\Entity\QuestionType:
            number: 5
            custom_formatters:
                libelle: {method: sentence, parameters: [2] }
        SceauBundle\Entity\Question:
            number: 100
            custom_formatters:
                libelle: {method: sentence, parameters: [2]}
                libelleCourt: {method: sentence, parameters: [1]}
                texteSupp: {method: null}
                ordre: {method: numberBetween, parameters: [0,200]}
                dateDebut: {method: null}
                dateFin: {method: null}
                page: {method: numberBetween, parameters: [1,10]}
                actif: {method: boolean, parameters: [100]}
                cache: {method: boolean, parameters: [0]}
                visible: {method: null}
                obligatoire: {method: boolean, parameters: [0]}
        SceauBundle\Entity\Reponse:
            number: 250
            custom_formatters:
                libelle: {method: sentence, parameters: [2]}
                libelleCourt: {method: sentence, parameters: [1]}
                ordre: {method: numberBetween, parameters: [0,200]}
                precision: {method: boolean, parameters: [0]}
                actif: {method: boolean, parameters: [100]}
        SceauBundle\Entity\Commande:
            number: 1000
            custom_formatters:
                email: {method: email }
                prenom: {method: firstName }
                nom: {method: lastName }
                date: {method: dateTimeThisYear }
                reference: {method: numerify, parameters: ['##########'] }
                montant: {method: randomFloat, parameters: [2] }
                dateutilisation : {method: null }
                donnees : {method: null }
        SceauBundle\Entity\Pays:
            number: 200
            custom_formatters:
                libelle: {method: word }
        SceauBundle\Entity\Coordonnee:
            number: 100
            custom_formatters:
                adresse: {method: sentence, parameters: [2]}
                codePostal: {method: numberBetween, parameters: [1,100000]}
                ville: {method: word }
        SceauBundle\Entity\Civilite:
            number: 3
            custom_formatters:
                libelle: {method: lexify, parameters: ['???'] }         
        SceauBundle\Entity\Avatar:
            number: 100
        SceauBundle\Entity\Email:
            number: 100            
            custom_formatters:
                email: {method: email }
                principal: {method: boolean, parameters: [100]}
                dateConfirmation: {method: dateTimeThisYear }                
        SceauBundle\Entity\MembreStatut:
            number: 5
            custom_formatters:
                libelle: {method: word }                
        SceauBundle\Entity\Membre:
            number: 100
            custom_formatters:
                nom: {method: lastName }
                prenom: {method: firstName }
                pseudo: {method: word, unique: true }
                dateCreation: {method: dateTimeThisYear }
        SceauBundle\Entity\Questionnaire:
            number: 1000
            custom_formatters:
                email: {method: email }
                dateInsertion: {method: dateTimeThisYear }
                datePrevEnvoi: {method: dateTimeThisYear }
                dateEnvoi: {method: dateTimeThisYear }
                dateOuverture: {method: dateTimeThisYear }
                dateReponse: {method: dateTimeThisYear }
                datePrevRelance: {method: null }
                dateRelance: {method: null }
                actif: {method: boolean, parameters: [100]}
                sousSite: {method: null }
        SceauBundle\Entity\QuestionnaireReponse:
            number: 2500
            custom_formatters:
                commentaire: {method: text, parameters: [500]}
                note: {method: numberBetween, parameters: [1,10]}
        SceauBundle\Entity\DroitDeReponse:
            number: 50
            custom_formatters:
                commentaire: {method: text, parameters: [700]}
                dateInsertion: {method: dateTimeThisYear }
                dateSuppression: {method: null }
                actif: {method: boolean, parameters: [100]}