    # This file is a "template" of what your parameters.yml file should look like
parameters:
    database_driver: pdo_pgsql
    database_host: localhost
    database_port: 5432
    database_name: sceau
    database_user: ragoupadysagadevin
    database_password: null

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null

    locale: fr
    secret: RobertTenaif

    logger_nb_max_fichier: 30
    memcache_host: localhost
    memcache_port: 11211

    widget_path:        "var/extranet/widget/"
    fianet_static_site: "https://static.fia-net.com/site_fianet"
