sceau_extranet:
    resource: "@SceauBundle/Controller/Extranet"
    type:     annotation
    prefix:   /extranet/{_locale}/
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en

sceau_webservice:
    resource: "@SceauBundle/Controller/Webservice"
    type:     annotation
    prefix:   /webservice/{_locale}/
    defaults: { _locale: fr }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"