sceau_admin:
    resource: "@SceauBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin/

sceau_extranet:
    resource: "@SceauBundle/Controller/Extranet"
    type:     annotation
    prefix:   /extranet/{_locale}/
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en

sceau_site:
    resource: "@SceauBundle/Controller/Site"
    type:     annotation
    prefix:   /site/{_locale}/
    defaults: { _locale: fr }
    requirements:
        _locale: fr|en

sceau_webservice:
    resource: "@SceauBundle/Controller/Webservice"
    type:     annotation
    prefix:   /webservice/{_locale}/
    defaults: { _locale: fr }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"