<?php

namespace FIANET\SceauBundle\Entity;

/**
 * QuestionStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
