SceauBundle\Entity\DroitDeReponse:
    group_sequence_provider: true
    properties:
        commentaire:
            - NotBlank:
                message: "constraints.droit_de_reponse_not_blank"
                groups: [validation]
            - Length:
                min: 4
                max: 700
                minMessage: "constraints.droit_de_reponse_nb_car_min_nok"
                maxMessage: "constraints.droit_de_reponse_nb_car_max_nok"
                groups: [validation]

SceauBundle\Entity\Flux:
    group_sequence_provider: true
    properties:
        xml:
            - NotNull:
                message: "constraints.flux_xml_not_null"
                groups: [reception1]
            - NotBlank:
                message: "constraints.flux_xml_not_blank"
                groups: [reception2]
        ip:
            - Ip:
                message: "constraints.flux_ip"
                groups: [reception3]
        checksum:
            - NotNull:
                message: "constraints.flux_checksum_not_null"
                groups: [reception4]
            - NotBlank:
                message: "constraints.flux_checksum_not_blank"
                groups: [reception5]

    constraints:
        - SceauBundle\Validator\Constraints\FluxChecksum:
            groups: [reception6]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: checksum
            message: "constraints.flux_xml_doublon"
            groups: [reception7]
        - SceauBundle\Validator\Constraints\FluxXmlFormat:
            groups: [reception8]
        - SceauBundle\Validator\Constraints\FluxXmlContenu:
            groups: [validation]

SceauBundle\Entity\Relance:
    properties:
        objet:
            - Length:
                max: 255
                maxMessage: "constraints.relance_objet_nb_car_max"

SceauBundle\Entity\Reponse:
    properties:
        libelle:
             - NotBlank:
                message: "constraints.reponse.libelle_not_blank"
                groups: [globale, perso]
             - Length:
                max: 100
                maxMessage: "constraints.reponse.libelle_max_length"
                groups: [globale, perso]

SceauBundle\Entity\Question:
    properties:
        libelle:
            - NotBlank:
                message: "constraints.question.libelle_not_blank"
                groups: [globale, perso]
            - Length:
                max: 100
                maxMessage: "constraints.question.libelle_max_length"
                groups: [globale, perso]
        dateDebut:
            - NotNull:
                message: "constraints.question.date_debut_not_null"
                groups: [perso]
            - Date:
                message: "constraints.question.date_invalide"
                groups: [perso]
        dateFin:
            - NotNull:
                message: "constraints.question.date_fin_not_null"
                groups: [perso]
            - Date:
                message: "constraints.question.date_invalide"
                groups: [perso]
    constraints:
        - SceauBundle\Validator\Constraints\QuestionGlobale:
            groups: [globale, perso]
        - SceauBundle\Validator\Constraints\QuestionPerso:
            groups: [perso]