FIANET\SceauBundle\Entity\Flux:
    group_sequence:
        - Flux
        - reception
        - reception2
    properties:
        xml:
            - NotNull:
                message: "constraints.flux_xml_not_null"
                groups: [reception]
            - NotBlank:
                message: "constraints.flux_xml_not_blank"
                groups: [reception]
        checksum:
            - NotNull:
                message: "constraints.flux_checksum_not_null"
                groups: [reception]
            - NotBlank:
                message: "constraints.flux_checksum_not_blank"
                groups: [reception]
        ip:
            - Ip:
                message: "constraints.flux_ip"
                groups: [reception]
    constraints:
        - FIANET\SceauBundle\Validator\Constraints\FluxChecksum:
            groups: [reception]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: checksum
            message: "constraints.flux_xml_doublon"
            groups: [reception]
        - FIANET\SceauBundle\Validator\Constraints\FluxXml:
            groups: [reception2]