FIANET\SceauBundle\Entity\Flux:
    group_sequence_provider: true
    properties:
        xml:
            - NotNull:
                message: "constraints.flux_xml_not_null"
                groups: [reception]
            - NotBlank:
                message: "constraints.flux_xml_not_blank"
                groups: [reception]
        checksum:
            - NotNull:
                message: "constraints.flux_checksum_not_null"
                groups: [reception]
            - NotBlank:
                message: "constraints.flux_checksum_not_blank"
                groups: [reception]
        ip:
            - Ip:
                message: "constraints.flux_ip"
                groups: [reception]              
    constraints:
        - FIANET\SceauBundle\Validator\Constraints\FluxChecksum:
            groups: [reception]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: checksum
            message: "constraints.flux_xml_doublon"
            groups: [reception]
        - FIANET\SceauBundle\Validator\Constraints\FluxXmlFormat:
            groups: [reception2]
        - FIANET\SceauBundle\Validator\Constraints\FluxXmlContenu:
            groups: [validation]
            
FIANET\SceauBundle\Entity\DroitDeReponse:
    group_sequence_provider: true
    properties:
        commentaire:
            - NotBlank:
                message: "constraints.droit_de_reponse_not_blank"
                groups: [validation]               
            - Length:
                min: 4
                max: 700
                minMessage: "constraints.droit_de_reponse_nb_car_min_nok"
                maxMessage: "constraints.droit_de_reponse_nb_car_max_nok"
                groups: [validation]