<?php

namespace SceauBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeColonneCSVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeCSVColonneRepository extends EntityRepository
{
}
