<?php

namespace SceauBundle\Entity;

/**
 * CoordonneesClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordonneesClientRepository extends \Doctrine\ORM\EntityRepository
{
}
