<?php

namespace SceauBundle\Entity;

/**
 * MoyenPaimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoyenPaimentRepository extends \Doctrine\ORM\EntityRepository
{
}
