<?php

namespace SceauBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotationLibelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotationLibelleRepository extends EntityRepository
{
}
