<?php

namespace SceauBundle\Entity;

/**
 * RetraitMarchandiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetraitMarchandiseRepository extends \Doctrine\ORM\EntityRepository
{
}
