<?php

namespace SceauBundle\Entity;

/**
 * ServiceClientelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceClientelRepository extends \Doctrine\ORM\EntityRepository
{
}
