<?php

namespace SceauBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SiteTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteTypeRepository extends EntityRepository
{
}
